WizardMvc/Models/Step1Model.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WizardMvc.Models
{
    [Serializable]
    public class Step1Model
    {
        [Required]
        public string One { get; set; }
        public string Two { get; set; }
        public string Three { get; set; }
    }
}

WizardMvc/Models/Step2Model.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WizardMvc.Models
{
    [Serializable]
    public class Step2Model
    {
        [Required]
        public string Four { get; set; }
        public string Five { get; set; }
        public string Six { get; set; }
    }
}

WizardMvc/Models/Step3Model.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WizardMvc.Models
{
    [Serializable]
    public class Step3Model
    {
        [Required]
        public string Seven { get; set; }
        public string Eight { get; set; }
        public string Nine { get; set; }
    }
}

WizardMvc/Models/WizardModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WizardMvc.Models
{
    [Serializable]
    public class WizardModel
    {
        public WizardModel()
        {
            Step1 = new Step1Model();
            Step2 = new Step2Model();
            Step3 = new Step3Model();
        }

        public int CurrentStepIndex { get; set; }
        public Step1Model Step1 { get; set; }
        public Step2Model Step2 { get; set; }
        public Step3Model Step3 { get; set; }

    }

   
}

WizardMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WizardMvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

WizardMvc/Controllers/WizardAjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WizardMvc.Models;

namespace WizardMvc.Controllers
{
    public class WizardAjaxController : Controller
    {

        [ChildActionOnly]
        public ActionResult Index()
        {
            var wizard = new WizardModel();
            return PartialView(wizard);
        }

        [HttpPost]
        public ActionResult Step1(Step1Model step1, string action)
        {
            var wizard = SerializationUtility.Deserialize(Request.Form["wizard"]) as WizardModel;
            wizard.Step1 = step1;
            return GetWizardStep(wizard, action);
        }

        [HttpPost]
        public ActionResult Step2(Step2Model step2, string action)
        {
            var wizard = SerializationUtility.Deserialize(Request.Form["wizard"]) as WizardModel;
            wizard.Step2 = step2;
            return GetWizardStep(wizard, action);
        }

        [HttpPost]
        public ActionResult Step3(Step3Model step3, string action)
        {
            var wizard = SerializationUtility.Deserialize(Request.Form["wizard"]) as WizardModel;
            wizard.Step3 = step3;
            return GetWizardStep(wizard, action);
        }

        private ActionResult GetWizardStep(WizardModel wizard, string action)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(action) && action == "Next")
                {
                    wizard.CurrentStepIndex++;
                }
                else if (!string.IsNullOrEmpty(action) && action == "Previous")
                {
                    wizard.CurrentStepIndex--;
                }
                else
                {
                    // TODO: we have finished: all the step partial
                    // view models have passed validation => map them
                    // back to the domain model and do some processing with
                    // the results

                    return Content("thanks for filling this form", "text/plain");
                }
            }
            else if (!string.IsNullOrEmpty(action) && action == "Previous")
            {
                // Even if validation failed we allow the user to
                // navigate to previous steps
                wizard.CurrentStepIndex--;
            }
            return PartialView("Index", wizard);
        }
    }

}

WizardMvc/Controllers/WizardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WizardMvc.Models;

namespace WizardMvc.Controllers
{
    public class WizardController : Controller
    {

        public ActionResult Index()
        {
            var wizard = new WizardModel();
            return View(wizard);
        }

        [HttpPost]
        public ActionResult Step1(Step1Model step)
        {
            var wizard = SerializationUtility.Deserialize(Request.Form["wizard"]) as WizardModel;
            wizard.Step1 = step;
            return GetWizardStep(wizard);
        }

        [HttpPost]
        public ActionResult Step2(Step2Model step)
        {
            var wizard = SerializationUtility.Deserialize(Request.Form["wizard"]) as WizardModel;
            wizard.Step2 = step;
            return GetWizardStep(wizard);
        }

        [HttpPost]
        public ActionResult Step3(Step3Model step)
        {
            var wizard = SerializationUtility.Deserialize(Request.Form["wizard"]) as WizardModel;
            wizard.Step3 = step;
            return GetWizardStep(wizard);
        }

        private ActionResult GetWizardStep(WizardModel wizard)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(Request.Form["next"]) && Request.Form["next"] == "Next")
                {
                    wizard.CurrentStepIndex++;
                }
                else if (!string.IsNullOrEmpty(Request.Form["prev"]) && Request.Form["prev"] == "Previous")
                {
                    wizard.CurrentStepIndex--;
                }
                else
                {
                    // TODO: we have finished: all the step partial
                    // view models have passed validation => map them
                    // back to the domain model and do some processing with
                    // the results

                    return Content("thanks for filling this form", "text/plain");
                }
            }
            else if (!string.IsNullOrEmpty(Request.Form["prev"]) && Request.Form["prev"] == "Previous")
            {
                // Even if validation failed we allow the user to
                // navigate to previous steps
                wizard.CurrentStepIndex--;
            }
            return View("Index", wizard);
        }
    }

}

WizardMvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div id="formdiv" class="row">

    @{
        Html.RenderAction("index", "WizardAjax");
    }

</div>


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).ready(function () {
            init();
        });

        function init() {

            

            var submitActor = null;
            var $form = $('form');
            var $submitActors = $form.find('input[type=submit]');

            $submitActors.click(function (event) {
                submitActor = this;
            });

            $('form').off("submit").submit(function () {
                if ($("form").valid()) {

                    $.ajax({
                        url: this.action,
                        type: this.method,
                        data: $(this).serialize() + "&action=" + submitActor.value + "",
                        success: function (html) {
                            $('#formdiv').html(html);
                            init();
                           
                        }
                    });

                }
                return false;
            });
            $.validator.unobtrusive.parse("form");
        }
    </script>
}

WizardMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WizardMvc/Views/Wizard/Index.cshtml
@model WizardMvc.Models.WizardModel


@{
    var stepAction = "";
    switch (Model.CurrentStepIndex)
    {
        case 0:
            stepAction = "step1";
            break;
        case 1:
            stepAction = "step2";
            break;
        case 2:
            stepAction = "step3";
            break;
    }

}


<h3>Step @(Model.CurrentStepIndex + 1) out of 3</h3>

@using (Html.BeginForm(stepAction, "Wizard"))
{

    @Html.Hidden("wizard", SerializationUtility.Serialize(Model))

    switch (Model.CurrentStepIndex)
    {
        case 0:
            @Html.EditorFor(x => Model.Step1, null, "")
            break;
        case 1:
        @Html.EditorFor(x => Model.Step2, null, "")
            break;
        case 2:
        @Html.EditorFor(x => Model.Step3, null, "")
            break;
    }


    if (Model.CurrentStepIndex > 0)
    {
        <input type="submit" value="Previous" name="prev" />
    }

    if (Model.CurrentStepIndex < 2)
    {
        <input type="submit" value="Next" name="next" />
    }
    else
    {
        <input type="submit" value="Finish" name="finish" />
    }
}

WizardMvc/Views/WizardAjax/Index.cshtml
@model WizardMvc.Models.WizardModel


@{
    var stepAction = "";
    switch (Model.CurrentStepIndex)
    {
        case 0:
            stepAction = "step1";
            break;
        case 1:
            stepAction = "step2";
            break;
        case 2:
            stepAction = "step3";
            break;
    }

}


<h3>Step @(Model.CurrentStepIndex + 1) out of 3</h3>

@using (Html.BeginForm(stepAction, "WizardAjax"))
{

    @Html.Hidden("wizard", SerializationUtility.Serialize(Model))

    switch (Model.CurrentStepIndex)
    {
        case 0:
            @Html.EditorFor(x => Model.Step1,null,  "")
            break;
        case 1:
        @Html.EditorFor(x => Model.Step2, null, "")
            break;
        case 2:
        @Html.EditorFor(x => Model.Step3, null, "")
            break;
    }


    if (Model.CurrentStepIndex > 0)
    {
        <input type="submit" value="Previous" name="prev" class="cancel" />
    }

    if (Model.CurrentStepIndex < 2)
    {
        <input type="submit" value="Next" name="next" />
    }
    else
    {
        <input type="submit" value="Finish" name="finish" />
    }
}